# don't build tags, it's redundant
if: tag IS blank

language: node_js

env:
  global:
    # SAUCE_USERNAME
    - secure: "RV5GDStAKSxJncyaVfUrc/xlHXnX/ZYe1DVvlY3ykvKNdyaJKsER+hw29pe6kOO3I7L8SMDT33YXWdcFFp9Za07B5ElyRPvgI6LH9vPpPD5tTGiOug/MKkghR9HGmEUJMwh3e2fkfYex79xTS1AKd7F2pth/q58OMdxmP7krAV/ehIN3LnP6dCQA2GWVnYBDmyjyxVFhX2o3e92PhfrhGl+s8x2OOAGIt+0iwIj5A1rSAu6VF2AEKlkx8VCLNh/Bq9AjT2ZAySsm4Dt6jxrR9VPL6ljT5c+6NzeJaRpxQ71R5nXdRmn07W5AxEqfJFbXcYui30/usgUjtxBQNCb1NXt8q6Qj6p4p+mLIl9Tw53RIRYKaaQhk8lbdelKhnloZ+8/gxdsUZUbOtONJJBy+V8kjdUWU1s+2FRLes4iZf1zGIUCQbZfLbf1PvujEag6Xufs2Nb20rNOiw8W7fsokUEJ2SzbUa4sguXkhUtKTIPBS3s1TfTjKcNDdwUf7m4B912YJtJK14H+ekjgbSEZv8xt4fiUtxp8RIOv4JRvIVK+D5knFftuviO3ScrYCb2Q5VbYprO7wYhoXdMrDyk49C7cwqqMb3io+1ScOi4Ty5v3bWcA+QQp8aFUDmF8jPcPYbSEaMtozXFNu0EgNF/ui4MRMTVrCfpoy1fGwYVmj0Ek="
    # SAUCE_ACCESS_KEY
    - secure: "nenxUMUZFzvQ2vSdIJ9RZR3n/WER12mAkbDkITsmrgMLtZpjO4RprgA8q1ayOJ+OARBnhwVlEHG/epfotgxbJUZsgOE9hr6CXT3v6tVKrme1fazZTCSvH5YsJ3NXVCAJMFzoqOSQ3M+mkdFFPO6ReXr3FX1kngC16DZOuGnT3mhBuhIQ9FDcBTuyg/5KiQrcAAXKzwcfX6p77eKrDBvN3rTdsGce1609CklPO/WyQoTu4yGP6n7OHj2242HNhdcjMsNHGqFRaAUIXwj+sz+Q+091l0JYRYgjo1BX0wPcmF5o/Cer2TsVWiUf+BcqfgrGWrrrFR8UCDES3K5Y4P4MSEdnSXm9Ja7UuSRVmiiGSErqMxo41v5vz0WdbCTP7GoLZMCNU+EPpkdx5AVOpORys7mOlCT1IAySe/sAt9NCxg5xHvbU7MxQDtKfsWAI+6G8T6XCilEDSLx0xQ9vkBlRjaL2itvkyEbuU7jZ2t+HPqyXu7kDMJ0bnpiuSO+BSAWnmT9DpPK6d97LCQB5g6H5fnR4hHHVrIgtqUtfaaXuw3JMjgdlrTJwGDJyCUJPZ6A9uRX7ewSnv9uR7Tl8EGDZ8SWndm4ILTrZc3PIPCf1wAEwaZ+5L59R3HpUdrWjuJz+FCb0bmWbLPC8ZY0f0TwmjGeK9IYcVDMzpmTIpPa9JJc="

# https://docs.travis-ci.com/user/chrome
addons:
  sauce_connect: true

script:
  - npm run lint
  - npm run build
  - npm run test

notifications:
  slack:
    secure: QxxoUzmxZMZ+WM0q6gjHMHlYmt0ni/cx42oDHek/XjHw8fFiaeWED5t0n8M/GkvgJkNP9SiZNGI33hCgUFSt6BzTfR99YHI4UWaQYTtcbLbgC86FP7SnLBUuC/8Q78vj1UU8Qk6Tk1AQVh+XCl94MAMuJZg6r4KTfVREkGUEIM0/0yNk5luFOkuEC30H1q7mLHJ+fFmFfur2WvjwPL7KcyP/aVMpUrrnmBmsaZn1YPfTq4C3mgX2PhnXX297567FNNcUH7thrtmu0dQEuNM6F1bQHHmyTJc26qelo+F/2zeKHN6NXlWgnuQxD//ZPNMxlcNMpRjBzyTsWvZAQ1yGO2LtV6Ds2eYLBq3+8+BwQriyLxuI/rJatpgGDqEr4sfykZi+qrsdE0mA2gUvWlvYzDO+0jG3wu/stjajOJR22nqeCoIlUDj/ANNvb8VXJPA6oZgm5bVSicb1CknxeiUH5feIAz5AKpE9w8kSUr6lgPdZr5RYcWJ8Q3QQjwr+Bps2/zn/MVn9EUlyp+VeT31f273fev5ldruEfJf8yZadk9lQ7OBJiXWbtEsMsTZx6bXPfbgNac3dM+39KxS1P9QFGx1qsnSY6xLyS5nxRlJWWpaLWxJMMnuMwnUID/11ylUcuWJO37dE6V9w+cNMQfgve1Ztv4LetyUtDisL2OYVe3w=
    on_success: change
    on_failure: change
